name: 'QuantEcon Style Guide Checker'
description: 'Automated style guide compliance checking for QuantEcon lecture materials'
author: 'QuantEcon'

branding:
  icon: 'check-circle'
  color: 'blue'

inputs:
  mode:
    description: 'Review mode: "single" for one lecture, "bulk" for all lectures'
    required: true
  lectures-path:
    description: 'Path to lectures directory'
    required: false
    default: 'lectures/'
  anthropic-api-key:
    description: 'Anthropic API key for Claude Sonnet 4.5'
    required: true
  github-token:
    description: 'GitHub token for creating PRs and comments'
    required: true
  comment-body:
    description: 'Issue comment body (used in single mode to extract lecture name)'
    required: false
  llm-model:
    description: 'Specific Claude model to use (default: claude-sonnet-4-5-20250929)'
    required: false
    default: ''
  rule-categories:
    description: 'Comma-separated list of rule categories to check (leave empty for all)'
    required: false
    default: ''
  create-pr:
    description: 'Whether to create a PR with suggested changes'
    required: false
    default: 'true'
  pr-branch-prefix:
    description: 'Prefix for PR branch names'
    required: false
    default: 'style-guide'
  pr-labels:
    description: 'Comma-separated list of labels to add to the PR'
    required: false
    default: ''
  temperature:
    description: 'LLM temperature (0=deterministic, 1=creative). Lower values give more consistent results.'
    required: false
    default: '0'

outputs:
  pr-number:
    description: 'Number of the created pull request'
    value: ${{ steps.run-checker.outputs.pr-number }}
  pr-url:
    description: 'URL of the created pull request'
    value: ${{ steps.run-checker.outputs.pr-url }}
  issues-found:
    description: 'Number of style guide issues found'
    value: ${{ steps.run-checker.outputs.issues-found }}
  lectures-reviewed:
    description: 'Number of lectures reviewed'
    value: ${{ steps.run-checker.outputs.lectures-reviewed }}

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.github-token }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ github.action_path }}/requirements.txt

    - name: Run style checker
      id: run-checker
      shell: bash
      env:
        PYTHONPATH: ${{ github.action_path }}
        ANTHROPIC_API_KEY: ${{ inputs.anthropic-api-key }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        python ${{ github.action_path }}/style_checker/main.py \
          --mode "${{ inputs.mode }}" \
          --lectures-path "${{ inputs.lectures-path }}" \
          --llm-model "${{ inputs.llm-model }}" \
          --rule-categories "${{ inputs.rule-categories }}" \
          --create-pr "${{ inputs.create-pr }}" \
          --pr-branch-prefix "${{ inputs.pr-branch-prefix }}" \
          --temperature "${{ inputs.temperature }}" \
          --comment-body "${{ inputs.comment-body }}" \
          --repository "${{ github.repository }}"
